name: CI

on:
  pull_request:
    branches:
      - main
      - develop
permissions: {}
jobs:
  malware_security_scan:
    name: Malware Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
      - name: Malware Scanner
        uses: dell/common-github-actions/malware-scanner@c63b13266a54b23b4b7b6e9812e3e677357a5e64
        with:
          directories: .
          options: -ri
  run_skeleton_suite:
    name: Run Skeleton Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          repository: digital-preservation/droid
          path: 'droid'
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c #v6.0.0
        with:
          java-version: 21
          distribution: temurin
      - run: .github/scripts/branch_test.sh
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: signature-file.xml
          path: signature-file.xml
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        with:
          name: container-signature-file.xml
          path: container-signature-file.xml
            
          

