name: Verify PR Submission
on:
  push:
    branches-ignore:
      - main
      - develop
permissions: {}
jobs:
  check_pr_submission:
    runs-on: ubuntu-latest
    name: Verify PR file are in the correct format
    steps:
      - name: Checkout the code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Get files that have changed (compared to develop)
        run: |
          git add -N .
          git diff --name-status origin/develop...HEAD > changed_files.txt
      - name: Check changes are in the correct format
        run: |
          pip install -r .github/scripts/requirements.txt
          python3 .github/scripts/verify_pr_submission.py changed_files.txt
