name: Generate changelog
on:
  push:
    branches:
      - develop

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: true
      - run: |
          pip install -r .github/scripts/requirements.txt
          mkdir -p changelogs
          NEXT_VERSION=$(echo v$(curl https://api.github.com/repos/nationalarchives/pronom/releases/latest | jq -r '.name | ltrimstr("V") | tonumber + 1'))
          python .github/scripts/append_to_changelog.py $GITHUB_SHA $NEXT_VERSION
          git config user.email "41898752+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add changelogs | true
          git commit -m "Update changelog $NEXT_VERSION" | true
          git push -u origin develop
        env:
          GITHUB_TOKEN: ${{ github.token }}
